# Creation of Array

In [1]:
# Exp: 5

In [ ]:
# Aim : Creation of Array (1D,2D and Multidimennsional array) using numpy

In [1]:
# Name : Rushikesh Nilkhan
# Roll.No : 43
# sec : B
# Subject : ET1

In [2]:
import numpy as np

In [3]:
arr1=np.array([10,20,30,40,50])

In [4]:
arr1

array([10, 20, 30, 40, 50])

In [5]:
arr2=np.array([[10,20,30,40,50],[60,70,80,90,100]])

In [6]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [7]:
arr3=np.array([[10,20,30,40,50],[60,70,80,90,100],[15,25,35,45,55]])

In [9]:
arr3

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [ 15,  25,  35,  45,  55]])